---
# Source: shifu_chart/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: deviceshifu-rtspcamera-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverImage: "edgenesis/camera-python:v0.0.5"
    driverSku: "T1Pro"
  instructions: |
    instructionSettings:
      defaultTimeoutSeconds: -1
    instructions:
      "capture":
      "info":
      "stream":
  telemetries: |
    telemetrySettings:
      telemetryUpdateIntervalInMilliseconds: 6000
    telemetries:
---
# Source: shifu_chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-rtspcamera-deployment
  name: deviceshifu-rtspcamera
  namespace: deviceshifu
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: deviceshifu-rtspcamera-deployment
  type: NodePort
---
# Source: shifu_chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deviceshifu-rtspcamera-deployment
  name: deviceshifu-rtspcamera-deployment
  namespace: deviceshifu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deviceshifu-rtspcamera-deployment
  template:
    metadata:
      labels:
       app: deviceshifu-rtspcamera-deployment
    spec:
      nodeSelector:
        type: worker
      containers:
        - image: edgehub/deviceshifu-http-http:v0.24.0
          name: deviceimg
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: deviceshifu-config
              mountPath: "/etc/edgedevice/config"
              readOnly: true
          env:
            - name: EDGEDEVICE_NAME
              value: edgedevice-rtspcamera
            - name: EDGEDEVICE_NAMESPACE
              value: devices
        - image: edgenesis/camera-python:v0.0.5
          name: camera-python
          ports: 
          - containerPort: 11112
          env:
          - name: IP_CAMERA_ADDRESS
            value: "10.11.70.180"
          - name: IP_CAMERA_CONTAINER_PORT
            value: "11112"
          - name: IP_CAMERA_HTTP_PORT
            value: "80"
          - name: IP_CAMERA_PASSWORD
            value: "password"
          - name: IP_CAMERA_RTSP_PORT
            value: "554"
          - name: IP_CAMERA_USERNAME
            value: "admin"
          - name: PYTHONUNBUFFERED
            value: "1"
      volumes:
      - name: deviceshifu-config
        configMap:
          name: deviceshifu-rtspcamera-configmap
      serviceAccountName: edgedevice-sa
---
# Source: shifu_chart/templates/edgedevice.yaml
apiVersion: shifu.edgenesis.io/v1alpha1
kind: EdgeDevice
metadata:
  name: edgedevice-rtspcamera
  namespace: devices
spec:
  sku: "T1Pro"
  connection: Ethernet
  address: "localhost:11112"
  protocol: HTTP
  customMetadata:
      "description" : "description"
      "vendor" : "Reolink"
